name: Create GitHub Release

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Toolchain
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: "^1.0.1"

      - name: Report Tool Versions
        run: foreman list

      - name: Get Release Details
        shell: bash
        run: echo "PROJECT_VERSION=`grep -Po '(?<=version = ")([^"]+)' wally.toml`" >> $GITHUB_ENV

      - name: Set Release Filename
        shell: bash
        run: |
          echo "RELEASE_FILENAME=${{ github.event.repository.name }}-$PROJECT_VERSION.rbxm" >> $GITHUB_ENV

      - name: Install Dependencies
        run: wally install

      - name: Build Project
        run: rojo build default.project.json -o $RELEASE_FILENAME

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.PROJECT_VERSION }}
          tag_name: ${{ env.PROJECT_VERSION }}
          fail_on_unmatched_files: true
          files: |
            ${{ env.RELEASE_FILENAME }}
          draft: true
